# Generated by Django 3.0.5 on 2020-04-02 16:56
from django.contrib.auth.models import User
from django.db import migrations


def create_superuser(apps, schema_editor):
    User.objects.create_superuser(
        username='admin',
        password='admin',
        email='admin@simplesocial.com'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
